### ISSUE TITLE
Compilation error when using USD 20.11

### ISSUE THREAD

**Issue by cpichard** [Autodesk/arnold-usd#1553]
**Describe the bug**
The most recent version of arnold-usd doesn't compile with 20.11, it errors with:
`libs\render_delegate\reader.cpp(15): fatal error C1083: Cannot open include file: 'pxr/imaging/hio/image.h': No such file or directory`
