### PR TITLE
Build fixes

### PR DESCRIPTION
**Pull request by frenchdog**
**Changes proposed in this pull request**
- Add missing "main" plugInfo.json file
- Fix compilation error on OSX and missing library in usd_translator

### CODE REVIEW

File: render_delegate/material.cpp [hunk 1]
```diff
@@ -358,8 +358,8 @@ void HdArnoldMaterial::Sync(HdSceneDelegate* sceneDelegate, HdRenderParam* rende
             const auto* volumeNetwork = TfMapLookupPtr(map.map, HdMaterialTerminalTokens->volume);
 #else
             const auto* surfaceNetwork = TfMapLookupPtr(map.map, UsdImagingTokens->bxdf);
-            const auto* displacementNetwork = nullptr;
-            const auto* volumeNetwork = nullptr;
+            const auto displacementNetwork = nullptr;
+            const auto volumeNetwork = nullptr;
```
Comment (sirpalee) [inline render_delegate/material.cpp]: This compiles fine on 10.15 and the toolset there, so type inference must have been improved. Which MacOS/Compiler version are you using?

Instead of auto, we could just use `decltype(surfaceNetwork)` for the `displacementNetwork` and `volumeNetwork` type. This better at expressing that `displacementNetwork` and `volumeNetwork` are the same type as `surfaceNetwork` but they are initialized with a nullptr value.

Comment (frenchdog) [reply render_delegate/material.cpp]: Excellent suggestion! I will give it a try.
