### ISSUE TITLE
Need Help to Build with Houdini 21.0.596 HtoA 6.4.5.3

### ISSUE THREAD

**Issue by ZimuQin** [Autodesk/arnold-usd#2765]
Hi, 
I'm trying to build and replace the arnold usd procedural in HtoA because I want to use a custom asset resolver. However, although the build works fine, after my replacement of "usd_proc.so", I got this error when rendering: "Coding Error (secondary thread): in CreateRenderDelegate at line 91 of /home/prisms/builder-new/WeeklyDevTools21.0/dev_tools/src/usd/usd-25.05/USD-py3.11-qt6/pxr/imaging/hd/rendererPluginRegistry.cpp -- Couldn't find plugin for id HdArnoldRendererPlugin". I can add hdArnold plugin path to the environment variable PXR_PLUGINPATH_NAME, but then I got this error at render time instead: "Coding Error (secondary thread): in Define at line 131 of /home/prisms/builder-new/WeeklyDevTools21.0/dev_tools/src/usd/usd-25.05/USD-py3.11-qt6/pxr/base/tf/envSetting.cpp -- Multiple definitions of TfEnvSetting variable detected.  This is usually due to software misconfiguration.  Contact the build team for assistance.  (duplicate 'HDARNOLD_bucket_size')". FYI, if I uncheck the "Hydra" option in sop arnold usd node, the rendering works fine, but I suppose Hydra is the preferred way now, right? So is there anything I could do wrong with the build? I uploaded my custom.py that I used to build.

[custom.py](https://github.com/user-attachments/files/32433188/custom.py)

**Comment by cpichard** [comment]
Hi, for htoa you might want to replace the render delegate instead of the usd procedural, unless you absolutely want to use kick.
Currently the usd procedural usd_proc.so comes with its own embedded version of usd, so it can be used with kick without houdini. If you recompile it with shared houdini's usd version it will end up conflicting since it has the same hydra code as the render delegate hdArnold. With houdini you only need the render delegate hdArnold and I am not even sure you would need to recompile it for adding an asset resolver.

**Comment by ZimuQin** [comment]
> Hi, for htoa you might want to replace the render delegate instead of the usd procedural, unless you absolutely want to use kick. Currently the usd procedural usd_proc.so comes with its own embedded version of usd, so it can be used with kick without houdini. If you recompile it with shared houdini's usd version it will end up conflicting since it has the same hydra code as the render delegate hdArnold. With houdini you only need the render delegate hdArnold and I am not even sure you would need to recompile it for adding an asset resolver.

Thank you for the reply! Yes, I'm afraid that I have to use kick in some cases. I guess it is the same problem discussed before here: [https://github.com/Autodesk/arnold-usd/issues/1869](https://github.com/Autodesk/arnold-usd/issues/1869) So is there any plan to support custom resolver using usd procedural in the future? And for now, I cannot have usd procedural to work in Houdini with both Hydra translator and custom resolver, so I am stuck with the lagacy translator only? Or is there any trick that I can get the shared library of USD to work in the procedural?
