### ISSUE TITLE
The render delegate fails to build using gcc 4.8.5

### ISSUE THREAD

**Issue by sirpalee** [Autodesk/arnold-usd#641]
When building the render delegate using gcc 4.8.5, it fails with the following error:

```
render_delegate/camera.cpp: In lambda function:
render_delegate/camera.cpp:102:14: error: converting to ‘std::tuple<foundryInternal_v19_11_fn__pxrReserved__::TfToken, AtString>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = foundryInternal_v19_11_fn__pxrReserved__::TfToken&; _U2 = const AtString&; <template-parameter-2-3> = void; _T1 = foundryInternal_v19_11_fn__pxrReserved__::TfToken; _T2 = AtString]’
             }};
              ^
render_delegate/camera.cpp:102:14: error: converting to ‘std::tuple<foundryInternal_v19_11_fn__pxrReserved__::TfToken, AtString>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = foundryInternal_v19_11_fn__pxrReserved__::TfToken&; _U2 = const AtString&; <template-parameter-2-3> = void; _T1 = foundryInternal_v19_11_fn__pxrReserved__::TfToken; _T2 = AtString]’
render_delegate/camera.cpp:102:14: error: converting to ‘std::tuple<foundryInternal_v19_11_fn__pxrReserved__::TfToken, AtString>’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = foundryInternal_v19_11_fn__pxrReserved__::TfToken&; _U2 = const AtString&; <template-parameter-2-3> = void; _T1 = foundryInternal_v19_11_fn__pxrReserved__::TfToken; _T2 = AtString]’
```
